template = ""
rev_id = 11
template_sha = "211be85371b914c06257b37026553182562f3608"

[replacements]
__LICENSE__ = ""
__UND2C_SRC__ = "ru"
__UND2C_TRG__ = "vot"
__UNDEFINED_SOURCE__ = "Russian"
__UNDEFINED_TARGET__ = "Votic"
__UND_SRC__ = "rus"
__UND_TRG__ = "vot"
