template = ""
rev_id = 6
template_sha = "08de358f84ed88e430f0754209b276aa821f47c5"

[replacements]
__LICENSE__ = ""
__UND2C_SRC__ = "ru"
__UND2C_TRG__ = "vot"
__UNDEFINED_SOURCE__ = "Russian"
__UNDEFINED_TARGET__ = "Votic"
__UND_SRC__ = "rus"
__UND_TRG__ = "vot"
