template = ""
rev_id = 7
template_sha = "94893e7a5cd0adce3abaa3e278710450dd114995"

[replacements]
__LICENSE__ = ""
__UND2C_SRC__ = "ru"
__UND2C_TRG__ = "vot"
__UNDEFINED_SOURCE__ = "Russian"
__UNDEFINED_TARGET__ = "Votic"
__UND_SRC__ = "rus"
__UND_TRG__ = "vot"
